services:
  llng:
    image: yadd/lemonldap-ng-full
    ports:
      - "19876:80"
    environment:
      - SSODOMAIN=example.com
      - PORTAL=http://auth.example.com
      - LOGLEVEL=debug
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
